In [2]:
import pandas as pd
import numpy as np

# Load the CSV file to examine its contents
file_path = "data/2025-TGFBI-Pick-Tracker.csv"
df = pd.read_csv(file_path)

# Display basic information and the first few rows of the dataset
df.info(), df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          699 non-null    int64
 1   Player      699 non-null    object
 2   Pos         699 non-null    object
 3   ADP         600 non-null    float64
 4   Min         699 non-null    int64
 5   Max         699 non-null    int64
 6   Range       555 non-null    float64
 7   Unnamed: 7  0 non-null      float64
 8   996         446 non-null    float64
 9   997         445 non-null    float64
 10  998         447 non-null    float64
 11  999         446 non-null    float64
 12  1000        444 non-null    float64
 13  1001        442 non-null    float64
 14  1002        444 non-null    float64
 15  1003        448 non-null    float64
 16  1004        443 non-null    float64
 17  1005        446 non-null    float64
 18  1006        444 non-null    float64
 19  1007        446 non-null    float64
 20  1008        442 non-null    float64
 21  1009        444 non-null    float64
 22  1010        447 non-null    float64
 23  1011        447 non-null    float64
 24  1012        447 non-null    float64
 25  1013        447 non-null    float64
 26  1014        446 non-null    float64
 27  1015        443 non-null    float64
 28  1016        447 non-null    float64
 29  1017        446 non-null    float64
 30  1018        445 non-null    float64
 31  1019        444 non-null    float64
 32  1020        448 non-null    float64
 33  1021        445 non-null    float64
dtypes: float64(29), int64(3), object(2)
memory usage: 185.8+ KB

(None,
       ID           Player    Pos  ADP  Min  Max  Range  Unnamed: 7  996  997  \
 0   9810    Shohei Ohtani  UT, P  1.5    1    3    2.0         NaN  1.0  1.0
 1  10932   Bobby Witt Jr.     SS  1.7    1    3    2.0         NaN  2.0  2.0
 2   8956      Aaron Judge     OF  3.2    2    5    3.0         NaN  3.0  3.0
 3   8594     Jose Ramirez     3B  4.7    3    7    4.0         NaN  5.0  4.0
 4  11583  Elly De La Cruz     SS  4.7    1    8    7.0         NaN  4.0  5.0

    ...  1012  1013  1014  1015  1016  1017  1018  1019  1020  1021
 0  ...   3.0   2.0   1.0   2.0   1.0   1.0   1.0   1.0   2.0   1.0
 1  ...   1.0   1.0   2.0   1.0   2.0   3.0   2.0   2.0   1.0   2.0
 2  ...   2.0   3.0   5.0   4.0   3.0   2.0   3.0   3.0   3.0   3.0
 3  ...   4.0   5.0   3.0   3.0   5.0   5.0   5.0   4.0   4.0   4.0
 4  ...   5.0   4.0   4.0   5.0   4.0   4.0   6.0   5.0   5.0   5.0

 [5 rows x 34 columns])

In [3]:
df_clean = df  # Remove header row duplication
df_clean["ADP"] = pd.to_numeric(df_clean["ADP"], errors="coerce")
df_clean["Min"] = pd.to_numeric(df_clean["Min"], errors="coerce")
df_clean["Max"] = pd.to_numeric(df_clean["Max"], errors="coerce")
df_clean["Range"] = pd.to_numeric(df_clean["Range"], errors="coerce")
df_clean = df_clean.loc[df_clean['Min']>0]  # Remove header row duplication

# Sort by ADP to see top-ranked players
df_clean_sorted = df_clean.sort_values(by="Min")

In [4]:
df_clean.loc[(df_clean['Min']<200)&(df_clean['Range']>100)]

,ID,Player,Pos,ADP,Min,Max,Range,Unnamed: 7,996,997,...,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021
150,10207,Grayson Rodriguez,P,154.9,80,322,242.0,NaN,105.0,113.0,...,132.0,322.0,159.0,106.0,104.0,96.0,116.0,290.0,117.0,119.0
154,11118,Francisco Alvarez,C,157.2,106,346,240.0,NaN,133.0,144.0,...,146.0,138.0,140.0,149.0,168.0,145.0,121.0,159.0,151.0,178.0
170,9921,Lucas Erceg,P,174.2,90,253,163.0,NaN,213.0,131.0,...,225.0,178.0,137.0,229.0,241.0,135.0,172.0,127.0,239.0,142.0
176,11556,Spencer Steer,"1B, OF",180.0,119,257,138.0,NaN,165.0,170.0,...,210.0,195.0,233.0,202.0,181.0,203.0,140.0,207.0,250.0,199.0
180,8955,Brandon Nimmo,OF,183.2,147,249,102.0,NaN,149.0,195.0,...,249.0,186.0,203.0,219.0,183.0,158.0,174.0,170.0,170.0,191.0
187,8228,Jurickson Profar,OF,188.7,137,238,101.0,NaN,203.0,183.0,...,211.0,170.0,166.0,170.0,182.0,137.0,187.0,217.0,165.0,188.0
191,9639,Yandy Diaz,1B,191.3,137,258,121.0,NaN,204.0,194.0,...,193.0,210.0,207.0,186.0,172.0,181.0,213.0,167.0,213.0,200.0
197,9789,Tyler O'Neill,OF,198.0,103,250,147.0,NaN,250.0,211.0,...,219.0,206.0,196.0,196.0,103.0,212.0,176.0,202.0,188.0,195.0
199,11751,Jackson Holliday,2B,199.3,138,249,111.0,NaN,200.0,203.0,...,218.0,203.0,218.0,215.0,229.0,214.0,190.0,184.0,234.0,249.0
200,10331,Shane Baz,P,202.3,152,254,102.0,NaN,215.0,186.0,...,172.0,194.0,232.0,232.0,190.0,207.0,161.0,198.0,215.0,152.0
203,10072,Cedric Mullins,OF,207.5,131,242,111.0,NaN,205.0,232.0,...,182.0,174.0,206.0,237.0,187.0,219.0,196.0,221.0,187.0,204.0
209,11628,Ceddanne Rafaela,"SS, OF",212.3,150,284,134.0,NaN,227.0,284.0,...,192.0,196.0,198.0,181.0,204.0,217.0,185.0,213.0,265.0,247.0
212,9294,Carlos Estevez,P,212.9,164,293,129.0,NaN,186.0,270.0,...,221.0,185.0,270.0,208.0,206.0,253.0,209.0,208.0,216.0,194.0
213,10068,Brandon Lowe,2B,213.5,91,256,165.0,NaN,256.0,239.0,...,200.0,214.0,231.0,199.0,243.0,200.0,193.0,190.0,214.0,222.0
219,8223,Nolan Arenado,3B,220.8,158,268,110.0,NaN,197.0,223.0,...,158.0,216.0,202.0,234.0,268.0,227.0,232.0,225.0,244.0,226.0
230,11897,Jackson Jobe,P,231.8,161,291,130.0,NaN,244.0,238.0,...,202.0,232.0,217.0,264.0,232.0,225.0,235.0,241.0,200.0,251.0
232,10937,Connor Wong,C,233.5,169,295,126.0,NaN,234.0,218.0,...,216.0,295.0,209.0,214.0,233.0,264.0,260.0,259.0,190.0,230.0
233,8808,Kirby Yates,P,233.8,142,369,227.0,NaN,282.0,208.0,...,227.0,213.0,256.0,180.0,228.0,179.0,262.0,260.0,280.0,203.0
236,11421,Alec Burleson,OF,240.0,198,313,115.0,NaN,259.0,245.0,...,236.0,231.0,247.0,254.0,253.0,233.0,254.0,313.0,217.0,212.0
238,9764,Walker Buehler,P,241.6,110,277,167.0,NaN,230.0,229.0,...,268.0,257.0,242.0,255.0,213.0,244.0,228.0,253.0,261.0,229.0
239,9856,Willi Castro,"2B, 3B, SS, OF",241.6,179,290,111.0,NaN,253.0,290.0,...,256.0,242.0,237.0,235.0,225.0,236.0,229.0,249.0,226.0,234.0
242,8691,Max Muncy,3B,244.1,159,274,115.0,NaN,271.0,225.0,...,251.0,159.0,252.0,274.0,272.0,258.0,216.0,251.0,236.0,268.0
247,8658,Trevor Story,SS,247.5,178,290,112.0,NaN,251.0,273.0,...,235.0,233.0,246.0,256.0,178.0,267.0,220.0,247.0,290.0,233.0
251,11447,Ronel Blanco,P,252.9,199,313,114.0,NaN,252.0,230.0,...,242.0,255.0,199.0,231.0,266.0,257.0,218.0,236.0,224.0,214.0
253,8951,Jose Berrios,P,254.0,193,322,129.0,NaN,240.0,212.0,...,275.0,265.0,322.0,258.0,193.0,312.0,226.0,209.0,221.0,254.0
257,10245,Joey Bart,C,257.4,193,310,117.0,NaN,193.0,199.0,...,261.0,268.0,230.0,248.0,244.0,270.0,263.0,261.0,285.0,244.0
258,10296,Nathaniel Lowe,1B,257.8,170,297,127.0,NaN,290.0,291.0,...,231.0,263.0,251.0,236.0,230.0,283.0,231.0,267.0,297.0,241.0
261,10307,Parker Meadows,OF,259.7,151,303,152.0,NaN,289.0,303.0,...,252.0,249.0,249.0,273.0,287.0,276.0,274.0,274.0,276.0,248.0
262,9678,Brandon Woodruff,P,259.9,199,347,148.0,NaN,255.0,260.0,...,232.0,229.0,250.0,309.0,248.0,247.0,310.0,238.0,238.0,225.0
265,11154,Christopher Morel,"2B, 3B",264.3,159,298,139.0,NaN,263.0,285.0,...,250.0,262.0,266.0,277.0,284.0,235.0,253.0,266.0,278.0,273.0
269,8954,Michael Conforto,OF,265.3,142,312,170.0,NaN,261.0,262.0,...,292.0,142.0,239.0,259.0,276.0,277.0,238.0,278.0,251.0,267.0
275,11753,Evan Carter,OF,271.3,170,315,145.0,NaN,238.0,315.0,...,280.0,297.0,308.0,284.0,279.0,289.0,279.0,279.0,270.0,271.0
283,11980,Porter Hodge,P,286.4,198,395,197.0,NaN,291.0,210.0,...,372.0,346.0,260.0,283.0,281.0,344.0,293.0,210.0,395.0,258.0
285,8170,Liam Hendriks,P,288.7,182,408,226.0,NaN,239.0,266.0,...,315.0,286.0,335.0,261.0,303.0,327.0,251.0,377.0,293.0,239.0
287,8666,Sean Manaea,P,292.0,191,422,231.0,NaN,276.0,250.0,...,278.0,316.0,299.0,293.0,385.0,313.0,275.0,220.0,264.0,301.0
296,11127,Jason Foley,P,300.7,176,379,203.0,NaN,284.0,340.0,...,370.0,275.0,344.0,271.0,379.0,309.0,307.0,292.0,260.0,327.0
299,11948,Roman Anthony,OF,304.0,193,341,148.0,NaN,337.0,341.0,...,316.0,292.0,290.0,324.0,299.0,329.0,309.0,337.0,291.0,340.0
305,12195,Kristian Campbell,2B,310.0,196,365,169.0,NaN,357.0,351.0,...,329.0,339.0,300.0,298.0,339.0,335.0,276.0,365.0,316.0,315.0
313,11754,Ben Joyce,P,319.0,190,412,222.0,NaN,334.0,263.0,...,404.0,328.0,190.0,342.0,369.0,356.0,NaN,300.0,300.0,350.0

In [5]:
df_clean['996']

0      1.0
1      2.0
2      3.0
3      5.0
4      4.0
      ...
595    NaN
596    NaN
597    NaN
598    NaN
599    NaN
Name: 996, Length: 600, dtype: float64

In [29]:
#996-1021

for lg in range(996,1021):
    df_clean[str(lg)] = pd.to_numeric(df_clean[str(lg)], errors="coerce")

/var/folders/6w/dlp9742d17v7x08hrlbn3d0r0000gn/T/ipykernel_22811/978309029.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[str(lg)] = pd.to_numeric(df_clean[str(lg)], errors="coerce")

In [35]:
df_clean.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       630, 644, 646, 654, 657, 660, 673, 677, 681, 697],
      dtype='int64', length=579)

In [37]:
df_clean['MDP'] = np.zeros(df_clean['ADP'].values.size)

for indx,mdp in enumerate(df_clean['MDP'].values):
    df_clean['MDP'].values[indx] = np.nanmedian(np.array([df_clean[str(lg)].values[indx] for lg in range(996,1021)]))

/var/folders/6w/dlp9742d17v7x08hrlbn3d0r0000gn/T/ipykernel_22811/2357493840.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['MDP'] = np.zeros(df_clean['ADP'].values.size)
/var/folders/6w/dlp9742d17v7x08hrlbn3d0r0000gn/T/ipykernel_22811/2357493840.py:4: RuntimeWarning: All-NaN slice encountered
  df_clean['MDP'].values[indx] = np.nanmedian(np.array([df_clean[str(lg)].values[indx] for lg in range(996,1021)]))

In [41]:
df_clean['DPdiff'] = df_clean['ADP']-df_clean['MDP']

/var/folders/6w/dlp9742d17v7x08hrlbn3d0r0000gn/T/ipykernel_22811/2224293199.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['DPdiff'] = df_clean['ADP']-df_clean['MDP']

In [47]:
# negative means guys reached (adp is higher than median)

df_clean_sorted = df_clean.sort_values(by="DPdiff")
df_clean_sorted.head(10)

,ID,Player,Pos,ADP,Min,Max,Range,Unnamed: 7,996,997,...,1014,1015,1016,1017,1018,1019,1020,1021,MDP,DPdiff
361,10760,Luis Gil,P,363.5,297,420,123.0,NaN,NaN,NaN,...,NaN,NaN,NaN,407.0,NaN,NaN,NaN,297.0,407.0,-43.5
347,10397,Geraldo Perdomo,SS,395.8,257,446,189.0,NaN,421.0,NaN,...,NaN,NaN,446.0,NaN,NaN,NaN,NaN,NaN,421.5,-25.7
463,9781,Brendan Rodgers,2B,414.0,361,444,83.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,437.0,NaN,437.0,-23.0
415,9107,Tyler Anderson,P,403.7,319,437,118.0,NaN,426.0,NaN,...,434.0,NaN,403.0,437.0,NaN,NaN,427.0,NaN,426.0,-22.3
363,12214,Hyeseong Kim,2B,377.0,314,441,127.0,NaN,NaN,NaN,...,339.0,NaN,NaN,NaN,399.0,NaN,314.0,NaN,399.0,-22.0
617,11331,Zac Veen,OF,417.4,339,445,106.0,NaN,NaN,NaN,...,NaN,NaN,445.0,418.0,443.0,NaN,NaN,NaN,438.0,-20.6
407,11615,Deyvison De Los Santos,1B,409.7,371,429,58.0,NaN,NaN,371.0,...,429.0,NaN,NaN,NaN,429.0,NaN,NaN,NaN,429.0,-19.3
392,10381,Bryan Abreu,P,383.7,280,439,159.0,NaN,420.0,389.0,...,NaN,NaN,NaN,NaN,NaN,NaN,429.0,427.0,403.0,-19.3
386,7736,Starling Marte,OF,405.3,316,449,133.0,NaN,NaN,NaN,...,NaN,NaN,423.0,NaN,432.0,NaN,411.0,NaN,423.0,-17.7
455,8694,J.P. Crawford,SS,403.7,365,426,61.0,NaN,NaN,NaN,...,NaN,NaN,420.0,NaN,NaN,NaN,365.0,NaN,420.0,-16.3

In [46]:
# positive means the tail is really long (i.e. guys waited)

df_clean_sorted = df_clean.sort_values(by="DPdiff",ascending=False)
df_clean_sorted.head(10)

,ID,Player,Pos,ADP,Min,Max,Range,Unnamed: 7,996,997,...,1014,1015,1016,1017,1018,1019,1020,1021,MDP,DPdiff
148,10207,Grayson Rodriguez,P,154.9,80,322,242.0,NaN,105.0,113.0,...,159.0,106.0,104.0,96.0,116.0,290.0,117.0,119.0,117.0,37.9
559,9452,Carson Kelly,C,406.5,370,443,73.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,443.0,370.0,36.5
496,11592,Edouard Julien,2B,396.0,370,422,52.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,422.0,370.0,26.0
380,10419,Noelvi Marte,3B,385.6,350,450,100.0,NaN,NaN,366.0,...,NaN,NaN,NaN,NaN,350.0,NaN,NaN,NaN,366.0,19.6
367,11147,Ha-Seong Kim,SS,361.9,258,436,178.0,NaN,436.0,400.0,...,413.0,NaN,NaN,293.0,337.0,NaN,346.0,435.0,344.0,17.9
409,10531,Jake Rogers,C,406.6,373,447,74.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,392.0,14.6
484,10626,Mike Yastrzemski,OF,404.3,386,425,39.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,415.0,425.0,391.0,13.3
562,8644,Kris Bryant,UT,433.5,421,446,25.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,421.0,NaN,NaN,446.0,421.0,12.5
352,9430,Luke Weaver,P,367.4,272,442,170.0,NaN,429.0,328.0,...,356.0,349.0,429.0,422.0,353.0,327.0,272.0,367.0,356.0,11.4
388,12194,Christian Moore,2B,385.1,331,447,116.0,NaN,447.0,NaN,...,NaN,NaN,NaN,NaN,365.0,NaN,NaN,379.0,374.0,11.1